"""adicionando tabela Produto NPR e criando relacionamento com Produto

Revision ID: 2f583dc51fa9
Revises: 4c6039f07b38
Create Date: 2025-11-24 08:30:17.453255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f583dc51fa9'
down_revision: Union[str, Sequence[str], None] = '4c6039f07b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProdutoNPR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prod', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('store', sa.String(), nullable=True),
    sa.Column('cod_bar', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_prod'], ['Produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProdutoNPR')
    # ### end Alembic commands ###
